# Generated by Django 5.1.4 on 2024-12-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecretMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.TextField()),
                ('Image', models.ImageField(blank=True, default='default.png', null=True, upload_to='customer_images/')),
            ],
        ),
    ]
