# Generated by Django 5.1.4 on 2024-12-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretmessage',
            name='ModifiedImage',
            field=models.ImageField(blank=True, null=True, upload_to='customer_images/'),
        ),
        migrations.AlterField(
            model_name='secretmessage',
            name='Image',
            field=models.ImageField(blank=True, default='customer_images/default.png', null=True, upload_to='customer_images/'),
        ),
    ]
