# Generated by Django 5.1.4 on 2025-01-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_decodemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='decodemessage',
            name='Extracted_File',
            field=models.FileField(blank=True, null=True, upload_to='decode_files/'),
        ),
        migrations.AddField(
            model_name='secretmessage',
            name='File',
            field=models.FileField(blank=True, null=True, upload_to='customer_files/'),
        ),
    ]
