# Generated by Django 5.1.4 on 2025-01-21 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_decodemessage_extracted_file_secretmessage_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decodemessage',
            name='Extracted_File',
        ),
    ]
