# Generated by Django 5.1.4 on 2025-01-22 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_decodemessage_extracted_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decodemessage',
            name='Message',
        ),
    ]
