# Generated by Django 5.1.4 on 2025-01-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_decodemessage_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretmessage',
            name='ModifiedImage',
            field=models.ImageField(blank=True, null=True, upload_to='modified_images/'),
        ),
    ]
