# Generated by Django 5.1.4 on 2025-02-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_secretmessage_modifiedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecodeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='decode_images/')),
            ],
        ),
        migrations.CreateModel(
            name='EncodeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(blank=True, null=True, upload_to='customer_files/')),
                ('Image', models.ImageField(blank=True, default='customer_images/default.png', null=True, upload_to='customer_images/')),
                ('ModifiedImage', models.ImageField(blank=True, null=True, upload_to='modified_images/')),
            ],
        ),
        migrations.CreateModel(
            name='EncodeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.TextField()),
                ('Image', models.ImageField(upload_to='encode_images/')),
                ('ModifiedImage', models.ImageField(blank=True, null=True, upload_to='modified_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='SecretMessage',
        ),
    ]
